-- Portfolio Remote DB Migration Script
-- Safe to run multiple times - only adds columns if missing

PRINT 'Starting Portfolio DB migration...';

-- GalleryJson
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'GalleryJson')
BEGIN ALTER TABLE Projects ADD GalleryJson NVARCHAR(MAX) NULL; PRINT 'Added GalleryJson'; END
ELSE PRINT 'GalleryJson already exists';

-- ResponsibilitiesJson
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'ResponsibilitiesJson')
BEGIN ALTER TABLE Projects ADD ResponsibilitiesJson NVARCHAR(MAX) NULL; PRINT 'Added ResponsibilitiesJson'; END
ELSE PRINT 'ResponsibilitiesJson already exists';

-- ReactionsCount
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'ReactionsCount')
BEGIN ALTER TABLE Projects ADD ReactionsCount INT NOT NULL DEFAULT 0; PRINT 'Added ReactionsCount'; END
ELSE PRINT 'ReactionsCount already exists';

-- Views
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Views')
BEGIN ALTER TABLE Projects ADD Views INT NOT NULL DEFAULT 0; PRINT 'Added Views'; END
ELSE PRINT 'Views already exists';

-- IsFeatured
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'IsFeatured')
BEGIN ALTER TABLE Projects ADD IsFeatured BIT NOT NULL DEFAULT 0; PRINT 'Added IsFeatured'; END
ELSE PRINT 'IsFeatured already exists';

-- Projects _Ar translation columns
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Title_Ar')
BEGIN ALTER TABLE Projects ADD Title_Ar NVARCHAR(500) NULL; PRINT 'Added Title_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Description_Ar')
BEGIN ALTER TABLE Projects ADD Description_Ar NVARCHAR(MAX) NULL; PRINT 'Added Description_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Summary_Ar')
BEGIN ALTER TABLE Projects ADD Summary_Ar NVARCHAR(MAX) NULL; PRINT 'Added Summary_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Category_Ar')
BEGIN ALTER TABLE Projects ADD Category_Ar NVARCHAR(200) NULL; PRINT 'Added Category_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Tags_Ar')
BEGIN ALTER TABLE Projects ADD Tags_Ar NVARCHAR(500) NULL; PRINT 'Added Tags_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Niche_Ar')
BEGIN ALTER TABLE Projects ADD Niche_Ar NVARCHAR(200) NULL; PRINT 'Added Niche_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Company_Ar')
BEGIN ALTER TABLE Projects ADD Company_Ar NVARCHAR(200) NULL; PRINT 'Added Company_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Duration_Ar')
BEGIN ALTER TABLE Projects ADD Duration_Ar NVARCHAR(100) NULL; PRINT 'Added Duration_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Language_Ar')
BEGIN ALTER TABLE Projects ADD Language_Ar NVARCHAR(100) NULL; PRINT 'Added Language_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Architecture_Ar')
BEGIN ALTER TABLE Projects ADD Architecture_Ar NVARCHAR(200) NULL; PRINT 'Added Architecture_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Projects' AND COLUMN_NAME = 'Status_Ar')
BEGIN ALTER TABLE Projects ADD Status_Ar NVARCHAR(100) NULL; PRINT 'Added Status_Ar'; END

-- RepliesJson for comments
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ProjectComments' AND COLUMN_NAME = 'RepliesJson')
BEGIN ALTER TABLE ProjectComments ADD RepliesJson NVARCHAR(MAX) NULL; PRINT 'Added RepliesJson'; END
ELSE PRINT 'RepliesJson already exists';

-- KeyFeatures _Ar columns
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ProjectKeyFeatures' AND COLUMN_NAME = 'Title_Ar')
BEGIN ALTER TABLE ProjectKeyFeatures ADD Title_Ar NVARCHAR(500) NULL; PRINT 'Added KeyFeatures.Title_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ProjectKeyFeatures' AND COLUMN_NAME = 'Description_Ar')
BEGIN ALTER TABLE ProjectKeyFeatures ADD Description_Ar NVARCHAR(MAX) NULL; PRINT 'Added KeyFeatures.Description_Ar'; END

-- Changelog _Ar columns
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ProjectChangelogs' AND COLUMN_NAME = 'Title_Ar')
BEGIN ALTER TABLE ProjectChangelogs ADD Title_Ar NVARCHAR(500) NULL; PRINT 'Added Changelog.Title_Ar'; END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ProjectChangelogs' AND COLUMN_NAME = 'Description_Ar')
BEGIN ALTER TABLE ProjectChangelogs ADD Description_Ar NVARCHAR(MAX) NULL; PRINT 'Added Changelog.Description_Ar'; END

PRINT 'Migration completed successfully!';
