name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'Portfolio.API/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Portfolio.API/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Portfolio.API

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    # Uncomment when unit tests are added
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal --configuration Release
